
import requests
from Auth import GetAuthToken as Auth

# Generate Helix Auth Token
helixToken= Auth()
methodheaders = {
        'Authorization': helixToken
}
jsonresponse = {
    "entries": [
        {
            "values": {
                "Work Log ID": "CWL000000000553",
                "Submitter": "Seth",
                "Submit Date": "2023-08-22T11:01:28.000+0000",
                "Assigned To": "",
                "Last Modified By": "Seth",
                "Last Modified Date": "2023-08-22T11:01:28.000+0000",
                "Status": "Enabled",
                "Short Description": ".",
                "Status History": "",
                "Notifier Listening": "Not Listening",
                "Assignee Groups": "2147480213;2000000129;",
                "Locale": "",
                "InstanceId": "AGGHE12CCOVBFARZS706RZS706ICDQ",
                "Record ID": "AGGHE12CCOVBFARZS706RZS706ICDQ",
                "Mode": "",
                "Vendor Assignee Groups": "",
                "Vendor Assignee Groups_parent": "",
                "Assignee Groups_parent": "",
                "z1G Multi-language": "",
                "z1G Enable French": "",
                "z1G Enable German": "",
                "z1G Enable Spanish": "",
                "z1G Enable User Defined 1": "",
                "z1G Enable User Defined 2": "",
                "z1G InitComplete": "",
                "z1G_Use_Custom_Prefix": "",
                "z1G_ChangeIDPrefix": "",
                "z1G_ChangeTaskIDPrefix": "",
                "z1D_DirtyFlag": "",
                "z1D_DirtyFlagAssociations": "",
                "z1D_Topic": "",
                "z1D_PrefixResult": "",
                "z1D_PrefixHolder": "",
                "z1D_UserAction": "",
                "DataTags": "",
                "Needs Attention": "",
                "MessageId": "",
                "SR_Instanceid": "SWGHE12CCOVBFARZS706RZS706ICDR",
                "z1D_WorkInfoToolTip_Info": "",
                "Attachment #1": "",
                "z1D_FileNameAttach2": "",
                "z1D_FileNameAttach3": "",
                "z1D_WorkInfoNote_DefaultMsg": "",
                "z1D_WorkInfo_NoteDefaultMsg": "",
                "z1D_WorkInfo_FileDefaultMsg": "",
                "z1D_WorkInfoFile_DefaultMsg": "",
                "AttachmentSourceFormName": "",
                "AttachmentSourceGUID": "",
                "z1D_ConfirmGroup": "",
                "Chat Session ID": "",
                "Broker Vendor Name": "",
                "Broker Vendor Ticket Id": "",
                "z1D_SkipIfSmartITInstalled": "",
                "NeedsAttentionCCS_Setting": "true",
                "ActivityValueChar_0": "@[Seth Potter]|Seth|(user)",
                "ActivityValueChar_1": "test work log",
                "ActivityValueChar_2": "",
                "ActivityValueChar_3": "",
                "ActivityValueSelection_0": "",
                "ActivityValueSelection_1": "",
                "ActivityValueSelection_2": "",
                "ActivityValueSelection_3": "",
                "SV_Activity_Display": "",
                "FileNameAttachment1": "",
                "FileNameAttachment2": "",
                "FileNameAttachment3": "",
                "SV_Ticket Summary": "@[Patient Record]|AGGHE12CCOVBFARZR27MRZR27MT3CP|(workorder)",
                "RequestCreatedFromDWP": "No",
                "DWP_SRID": "",
                "DWP_SRInstanceID": "",
                "z1D_WIS": "",
                "IsNotesRTFEnabled": "",
                "z1D_ApplicationGUID": "",
                "z1D_PropertyValue": "",
                "Description": "test work log",
                "Assigned Support Organization": "",
                "z1D Char01": "",
                "z1D Char02": "",
                "z1D Char03": "",
                "z1D Char04": "",
                "z1D Action": "",
                "z1D Integer01": "",
                "Assigned Group ID": "",
                "z1D Char05": "",
                "z1D Char06": "",
                "z1D Char07": "",
                "z1D Char08": "",
                "z1D Char09": "",
                "z1D Integer02": "",
                "z1D Integer03": "",
                "z1D Char10": "",
                "z1D Char11": "",
                "z1D Char12": "",
                "z1D Char13": "",
                "z1D Char14": "",
                "z1D Lastcount": "",
                "z1D Char15": "",
                "Detailed Description": "test work log",
                "Work Log Submit Date": "2023-08-22T11:01:28.000+0000",
                "Work Log Submitter": "Seth",
                "Work Log Type": "General Information",
                "Work Order ID": "WO0000000021381",
                "Assigned Group": "",
                "Assignee": "",
                "z1D Previous Operation": "",
                "z1D Page Indicator": "",
                "Assigned Support Company": "",
                "Work Order Task ID": "",
                "z1D Char16": "",
                "Shifts Flag": "",
                "Assigned Group Shift Name": "",
                "z1D Close Dialog": "",
                "Assigned Group Shift ID": "",
                "z2AF Work Log01": "",
                "z2AF Work Log02": "",
                "z2AF Work Log03": "",
                "z1D Work Log ID": "",
                "CHG Attachment ID": "",
                "Number of Attachments": 0,
                "Cross Reference ID": "",
                "Communication Source": "",
                "Total Time Spent": 0,
                "View Access": "Internal",
                "z1D Lastcount02": "",
                "z1D Integer04": "",
                "Request Number": "",
                "Work Order Number": "",
                "z1D Action02": "",
                "Secure Work Log": "No",
                "z1D Permission Group ID": "",
                "z1D Permission Group List": "",
                "Assignee Login ID": "",
                "Work Log Date": "2023-08-22T11:01:27.000+0000",
                "URL01": "",
                "URL02": "",
                "URL03": "",
                "Number of URLs": "",
                "WorkLog Action Status": "",
                "Assign WorkLog Flag": "No",
                "WorkLog Action Completed": "",
                "WorkOrder_EntryID": "WO0000000021381",
                "Infra. Change Task Entry ID": "",
                "z1D Copy To Request ID01": "",
                "z1D CHG Template ID": "",
                "z1D Copy To Request ID02": "",
                "z1D Copy To Request ID03": "",
                "SRM WorkLog ID": "",
                "Thumbnail 1": "",
                "Thumbnail 2": "",
                "Thumbnail 3": "",
                "z1D Assigned Group": ""
            },
            "_links": {
                "self": [
                    {
                        "href": "https://helixsjc814-demo-restapi.onbmc.com/api/arsys/v1/entry/WOI:WorkInfo/CWL000000000553"
                    }
                ]
            }
        },
        {
            "values": {
                "Work Log ID": "CWL000000000572",
                "Submitter": "Seth",
                "Submit Date": "2023-08-25T07:06:22.000+0000",
                "Assigned To": "",
                "Last Modified By": "Remedy Application Service",
                "Last Modified Date": "2023-08-25T07:07:11.000+0000",
                "Status": "Enabled",
                "Short Description": ".",
                "Status History": "",
                "Notifier Listening": "Not Listening",
                "Assignee Groups": "2147480213;2000000129;",
                "Locale": "",
                "InstanceId": "AGGHE12CCOVBFARZXQ4MRZXQ4MBP5T",
                "Record ID": "AGGHE12CCOVBFARZXQ4MRZXQ4MBP5T",
                "Mode": "",
                "Vendor Assignee Groups": "",
                "Vendor Assignee Groups_parent": "",
                "Assignee Groups_parent": "",
                "z1G Multi-language": "",
                "z1G Enable French": "",
                "z1G Enable German": "",
                "z1G Enable Spanish": "",
                "z1G Enable User Defined 1": "",
                "z1G Enable User Defined 2": "",
                "z1G InitComplete": "",
                "z1G_Use_Custom_Prefix": "",
                "z1G_ChangeIDPrefix": "",
                "z1G_ChangeTaskIDPrefix": "",
                "z1D_DirtyFlag": "",
                "z1D_DirtyFlagAssociations": "",
                "z1D_Topic": "",
                "z1D_PrefixResult": "",
                "z1D_PrefixHolder": "",
                "z1D_UserAction": "",
                "DataTags": "",
                "Needs Attention": "",
                "MessageId": "",
                "SR_Instanceid": "SWGHE12CCOVBFARZXQ4MRZXQ4MBP5U",
                "z1D_WorkInfoToolTip_Info": "",
                "Attachment #1": "",
                "z1D_FileNameAttach2": "",
                "z1D_FileNameAttach3": "",
                "z1D_WorkInfoNote_DefaultMsg": "",
                "z1D_WorkInfo_NoteDefaultMsg": "",
                "z1D_WorkInfo_FileDefaultMsg": "",
                "z1D_WorkInfoFile_DefaultMsg": "",
                "AttachmentSourceFormName": "",
                "AttachmentSourceGUID": "",
                "z1D_ConfirmGroup": "",
                "Chat Session ID": "",
                "Broker Vendor Name": "",
                "Broker Vendor Ticket Id": "",
                "z1D_SkipIfSmartITInstalled": "",
                "NeedsAttentionCCS_Setting": "true",
                "ActivityValueChar_0": "@[Seth Potter]|Seth|(user)",
                "ActivityValueChar_1": "test worklog",
                "ActivityValueChar_2": "",
                "ActivityValueChar_3": "",
                "ActivityValueSelection_0": "",
                "ActivityValueSelection_1": "",
                "ActivityValueSelection_2": "",
                "ActivityValueSelection_3": "",
                "SV_Activity_Display": "",
                "FileNameAttachment1": "Hi..Hello",
                "FileNameAttachment2": "",
                "FileNameAttachment3": "",
                "SV_Ticket Summary": "@[Patient Record]|AGGHE12CCOVBFARZR27MRZR27MT3CP|(workorder)",
                "RequestCreatedFromDWP": "No",
                "DWP_SRID": "",
                "DWP_SRInstanceID": "",
                "z1D_WIS": "",
                "IsNotesRTFEnabled": "",
                "z1D_ApplicationGUID": "",
                "z1D_PropertyValue": "",
                "Description": "test worklog",
                "Assigned Support Organization": "",
                "z1D Char01": "",
                "z1D Char02": "",
                "z1D Char03": "",
                "z1D Char04": "",
                "z1D Action": "",
                "z1D Integer01": "",
                "Assigned Group ID": "",
                "z1D Char05": "",
                "z1D Char06": "",
                "z1D Char07": "",
                "z1D Char08": "",
                "z1D Char09": "",
                "z1D Integer02": "",
                "z1D Integer03": "",
                "z1D Char10": "",
                "z1D Char11": "",
                "z1D Char12": "",
                "z1D Char13": "",
                "z1D Char14": "",
                "z1D Lastcount": "",
                "z1D Char15": "",
                "Detailed Description": "test worklog",
                "Work Log Submit Date": "2023-08-25T07:06:22.000+0000",
                "Work Log Submitter": "Seth",
                "Work Log Type": "General Information",
                "Work Order ID": "WO0000000021381",
                "Assigned Group": "",
                "Assignee": "",
                "z1D Previous Operation": "",
                "z1D Page Indicator": "",
                "Assigned Support Company": "",
                "Work Order Task ID": "",
                "z1D Char16": "",
                "Shifts Flag": "",
                "Assigned Group Shift Name": "",
                "z1D Close Dialog": "",
                "Assigned Group Shift ID": "",
                "z2AF Work Log01": {
                    "name": "Hi..Hello",
                    "sizeBytes": 79,
                    "href": "https://helixsjc814-demo-restapi.onbmc.com/api/arsys/v1/entry/WOI:WorkInfo/CWL000000000572/attach/z2AF%20Work%20Log01"
                },
                "z2AF Work Log02": "",
                "z2AF Work Log03": "",
                "z1D Work Log ID": "",
                "CHG Attachment ID": "",
                "Number of Attachments": 1,
                "Cross Reference ID": "",
                "Communication Source": "",
                "Total Time Spent": 0,
                "View Access": "Internal",
                "z1D Lastcount02": "",
                "z1D Integer04": "",
                "Request Number": "",
                "Work Order Number": "",
                "z1D Action02": "",
                "Secure Work Log": "No",
                "z1D Permission Group ID": "",
                "z1D Permission Group List": "",
                "Assignee Login ID": "",
                "Work Log Date": "2023-08-25T07:06:22.000+0000",
                "URL01": "",
                "URL02": "",
                "URL03": "",
                "Number of URLs": "",
                "WorkLog Action Status": "",
                "Assign WorkLog Flag": "No",
                "WorkLog Action Completed": "",
                "WorkOrder_EntryID": "WO0000000021381",
                "Infra. Change Task Entry ID": "",
                "z1D Copy To Request ID01": "",
                "z1D CHG Template ID": "",
                "z1D Copy To Request ID02": "",
                "z1D Copy To Request ID03": "",
                "SRM WorkLog ID": "",
                "Thumbnail 1": "",
                "Thumbnail 2": "",
                "Thumbnail 3": "",
                "z1D Assigned Group": ""
            },
            "_links": {
                "self": [
                    {
                        "href": "https://helixsjc814-demo-restapi.onbmc.com/api/arsys/v1/entry/WOI:WorkInfo/CWL000000000572"
                    }
                ]
            }
        },
        {
            "values": {
                "Work Log ID": "CWL000000000574",
                "Submitter": "Seth",
                "Submit Date": "2023-08-25T07:52:52.000+0000",
                "Assigned To": "",
                "Last Modified By": "Remedy Application Service",
                "Last Modified Date": "2023-08-25T07:53:12.000+0000",
                "Status": "Enabled",
                "Short Description": ".",
                "Status History": "",
                "Notifier Listening": "Not Listening",
                "Assignee Groups": "2147480213;2000000129;",
                "Locale": "",
                "InstanceId": "AGGHE12CCOVBFARZXSKERZXSKECVT8",
                "Record ID": "AGGHE12CCOVBFARZXSKERZXSKECVT8",
                "Mode": "",
                "Vendor Assignee Groups": "",
                "Vendor Assignee Groups_parent": "",
                "Assignee Groups_parent": "",
                "z1G Multi-language": "",
                "z1G Enable French": "",
                "z1G Enable German": "",
                "z1G Enable Spanish": "",
                "z1G Enable User Defined 1": "",
                "z1G Enable User Defined 2": "",
                "z1G InitComplete": "",
                "z1G_Use_Custom_Prefix": "",
                "z1G_ChangeIDPrefix": "",
                "z1G_ChangeTaskIDPrefix": "",
                "z1D_DirtyFlag": "",
                "z1D_DirtyFlagAssociations": "",
                "z1D_Topic": "",
                "z1D_PrefixResult": "",
                "z1D_PrefixHolder": "",
                "z1D_UserAction": "",
                "DataTags": "",
                "Needs Attention": "",
                "MessageId": "",
                "SR_Instanceid": "SWGHE12CCOVBFARZXSKERZXSKECVTK",
                "z1D_WorkInfoToolTip_Info": "",
                "Attachment #1": "",
                "z1D_FileNameAttach2": "",
                "z1D_FileNameAttach3": "",
                "z1D_WorkInfoNote_DefaultMsg": "",
                "z1D_WorkInfo_NoteDefaultMsg": "",
                "z1D_WorkInfo_FileDefaultMsg": "",
                "z1D_WorkInfoFile_DefaultMsg": "",
                "AttachmentSourceFormName": "",
                "AttachmentSourceGUID": "",
                "z1D_ConfirmGroup": "",
                "Chat Session ID": "",
                "Broker Vendor Name": "",
                "Broker Vendor Ticket Id": "",
                "z1D_SkipIfSmartITInstalled": "",
                "NeedsAttentionCCS_Setting": "true",
                "ActivityValueChar_0": "@[Seth Potter]|Seth|(user)",
                "ActivityValueChar_1": "second file",
                "ActivityValueChar_2": "",
                "ActivityValueChar_3": "",
                "ActivityValueSelection_0": "",
                "ActivityValueSelection_1": "",
                "ActivityValueSelection_2": "",
                "ActivityValueSelection_3": "",
                "SV_Activity_Display": "",
                "FileNameAttachment1": "Hi..Hello_2",
                "FileNameAttachment2": "",
                "FileNameAttachment3": "",
                "SV_Ticket Summary": "@[Patient Record]|AGGHE12CCOVBFARZR27MRZR27MT3CP|(workorder)",
                "RequestCreatedFromDWP": "No",
                "DWP_SRID": "",
                "DWP_SRInstanceID": "",
                "z1D_WIS": "",
                "IsNotesRTFEnabled": "",
                "z1D_ApplicationGUID": "",
                "z1D_PropertyValue": "",
                "Description": "second file",
                "Assigned Support Organization": "",
                "z1D Char01": "",
                "z1D Char02": "",
                "z1D Char03": "",
                "z1D Char04": "",
                "z1D Action": "",
                "z1D Integer01": "",
                "Assigned Group ID": "",
                "z1D Char05": "",
                "z1D Char06": "",
                "z1D Char07": "",
                "z1D Char08": "",
                "z1D Char09": "",
                "z1D Integer02": "",
                "z1D Integer03": "",
                "z1D Char10": "",
                "z1D Char11": "",
                "z1D Char12": "",
                "z1D Char13": "",
                "z1D Char14": "",
                "z1D Lastcount": "",
                "z1D Char15": "",
                "Detailed Description": "second file",
                "Work Log Submit Date": "2023-08-25T07:52:52.000+0000",
                "Work Log Submitter": "Seth",
                "Work Log Type": "General Information",
                "Work Order ID": "WO0000000021381",
                "Assigned Group": "",
                "Assignee": "",
                "z1D Previous Operation": "",
                "z1D Page Indicator": "",
                "Assigned Support Company": "",
                "Work Order Task ID": "",
                "z1D Char16": "",
                "Shifts Flag": "",
                "Assigned Group Shift Name": "",
                "z1D Close Dialog": "",
                "Assigned Group Shift ID": "",
                "z2AF Work Log01": {
                    "name": "Hi..Hello_2",
                    "sizeBytes": 53,
                    "href": "https://helixsjc814-demo-restapi.onbmc.com/api/arsys/v1/entry/WOI:WorkInfo/CWL000000000574/attach/z2AF%20Work%20Log01"
                },
                "z2AF Work Log02": "",
                "z2AF Work Log03": "",
                "z1D Work Log ID": "",
                "CHG Attachment ID": "",
                "Number of Attachments": 1,
                "Cross Reference ID": "",
                "Communication Source": "",
                "Total Time Spent": 0,
                "View Access": "Internal",
                "z1D Lastcount02": "",
                "z1D Integer04": "",
                "Request Number": "",
                "Work Order Number": "",
                "z1D Action02": "",
                "Secure Work Log": "No",
                "z1D Permission Group ID": "",
                "z1D Permission Group List": "",
                "Assignee Login ID": "",
                "Work Log Date": "2023-08-25T07:52:52.000+0000",
                "URL01": "",
                "URL02": "",
                "URL03": "",
                "Number of URLs": "",
                "WorkLog Action Status": "",
                "Assign WorkLog Flag": "No",
                "WorkLog Action Completed": "",
                "WorkOrder_EntryID": "WO0000000021381",
                "Infra. Change Task Entry ID": "",
                "z1D Copy To Request ID01": "",
                "z1D CHG Template ID": "",
                "z1D Copy To Request ID02": "",
                "z1D Copy To Request ID03": "",
                "SRM WorkLog ID": "",
                "Thumbnail 1": "",
                "Thumbnail 2": "",
                "Thumbnail 3": "",
                "z1D Assigned Group": ""
            },
            "_links": {
                "self": [
                    {
                        "href": "https://helixsjc814-demo-restapi.onbmc.com/api/arsys/v1/entry/WOI:WorkInfo/CWL000000000574"
                    }
                ]
            }
        },
        {
            "values": {
                "Work Log ID": "CWL000000000575",
                "Submitter": "Seth",
                "Submit Date": "2023-08-25T07:59:44.000+0000",
                "Assigned To": "",
                "Last Modified By": "Remedy Application Service",
                "Last Modified Date": "2023-08-25T08:01:12.000+0000",
                "Status": "Enabled",
                "Short Description": ".",
                "Status History": "",
                "Notifier Listening": "Not Listening",
                "Assignee Groups": "2147480213;2000000129;",
                "Locale": "",
                "InstanceId": "AGGHE12CCOVBFARZXSVKRZXSVKDBDQ",
                "Record ID": "AGGHE12CCOVBFARZXSVKRZXSVKDBDQ",
                "Mode": "",
                "Vendor Assignee Groups": "",
                "Vendor Assignee Groups_parent": "",
                "Assignee Groups_parent": "",
                "z1G Multi-language": "",
                "z1G Enable French": "",
                "z1G Enable German": "",
                "z1G Enable Spanish": "",
                "z1G Enable User Defined 1": "",
                "z1G Enable User Defined 2": "",
                "z1G InitComplete": "",
                "z1G_Use_Custom_Prefix": "",
                "z1G_ChangeIDPrefix": "",
                "z1G_ChangeTaskIDPrefix": "",
                "z1D_DirtyFlag": "",
                "z1D_DirtyFlagAssociations": "",
                "z1D_Topic": "",
                "z1D_PrefixResult": "",
                "z1D_PrefixHolder": "",
                "z1D_UserAction": "",
                "DataTags": "",
                "Needs Attention": "",
                "MessageId": "",
                "SR_Instanceid": "SWGHE12CCOVBFARZXSVKRZXSVKDBDS",
                "z1D_WorkInfoToolTip_Info": "",
                "Attachment #1": "",
                "z1D_FileNameAttach2": "",
                "z1D_FileNameAttach3": "",
                "z1D_WorkInfoNote_DefaultMsg": "",
                "z1D_WorkInfo_NoteDefaultMsg": "",
                "z1D_WorkInfo_FileDefaultMsg": "",
                "z1D_WorkInfoFile_DefaultMsg": "",
                "AttachmentSourceFormName": "",
                "AttachmentSourceGUID": "",
                "z1D_ConfirmGroup": "",
                "Chat Session ID": "",
                "Broker Vendor Name": "",
                "Broker Vendor Ticket Id": "",
                "z1D_SkipIfSmartITInstalled": "",
                "NeedsAttentionCCS_Setting": "true",
                "ActivityValueChar_0": "@[Seth Potter]|Seth|(user)",
                "ActivityValueChar_1": "thirs worklog",
                "ActivityValueChar_2": "",
                "ActivityValueChar_3": "",
                "ActivityValueSelection_0": "",
                "ActivityValueSelection_1": "",
                "ActivityValueSelection_2": "",
                "ActivityValueSelection_3": "",
                "SV_Activity_Display": "",
                "FileNameAttachment1": "Hi..Hello_3",
                "FileNameAttachment2": "Hi..Hello_2",
                "FileNameAttachment3": "Hi..Hello",
                "SV_Ticket Summary": "@[Patient Record]|AGGHE12CCOVBFARZR27MRZR27MT3CP|(workorder)",
                "RequestCreatedFromDWP": "No",
                "DWP_SRID": "",
                "DWP_SRInstanceID": "",
                "z1D_WIS": "",
                "IsNotesRTFEnabled": "",
                "z1D_ApplicationGUID": "",
                "z1D_PropertyValue": "",
                "Description": "thirs worklog",
                "Assigned Support Organization": "",
                "z1D Char01": "",
                "z1D Char02": "",
                "z1D Char03": "",
                "z1D Char04": "",
                "z1D Action": "",
                "z1D Integer01": "",
                "Assigned Group ID": "",
                "z1D Char05": "",
                "z1D Char06": "",
                "z1D Char07": "",
                "z1D Char08": "",
                "z1D Char09": "",
                "z1D Integer02": "",
                "z1D Integer03": "",
                "z1D Char10": "",
                "z1D Char11": "",
                "z1D Char12": "",
                "z1D Char13": "",
                "z1D Char14": "",
                "z1D Lastcount": "",
                "z1D Char15": "",
                "Detailed Description": "thirs worklog",
                "Work Log Submit Date": "2023-08-25T07:59:44.000+0000",
                "Work Log Submitter": "Seth",
                "Work Log Type": "General Information",
                "Work Order ID": "WO0000000021381",
                "Assigned Group": "",
                "Assignee": "",
                "z1D Previous Operation": "",
                "z1D Page Indicator": "",
                "Assigned Support Company": "",
                "Work Order Task ID": "",
                "z1D Char16": "",
                "Shifts Flag": "",
                "Assigned Group Shift Name": "",
                "z1D Close Dialog": "",
                "Assigned Group Shift ID": "",
                "z2AF Work Log01": {
                    "name": "Hi..Hello_3",
                    "sizeBytes": 24,
                    "href": "https://helixsjc814-demo-restapi.onbmc.com/api/arsys/v1/entry/WOI:WorkInfo/CWL000000000575/attach/z2AF%20Work%20Log01"
                },
                "z2AF Work Log02": {
                    "name": "Hi..Hello_2",
                    "sizeBytes": 53,
                    "href": "https://helixsjc814-demo-restapi.onbmc.com/api/arsys/v1/entry/WOI:WorkInfo/CWL000000000575/attach/z2AF%20Work%20Log02"
                },
                "z2AF Work Log03": {
                    "name": "Hi..Hello",
                    "sizeBytes": 79,
                    "href": "https://helixsjc814-demo-restapi.onbmc.com/api/arsys/v1/entry/WOI:WorkInfo/CWL000000000575/attach/z2AF%20Work%20Log03"
                },
                "z1D Work Log ID": "",
                "CHG Attachment ID": "",
                "Number of Attachments": 3,
                "Cross Reference ID": "",
                "Communication Source": "",
                "Total Time Spent": 0,
                "View Access": "Internal",
                "z1D Lastcount02": "",
                "z1D Integer04": "",
                "Request Number": "",
                "Work Order Number": "",
                "z1D Action02": "",
                "Secure Work Log": "No",
                "z1D Permission Group ID": "",
                "z1D Permission Group List": "",
                "Assignee Login ID": "",
                "Work Log Date": "2023-08-25T07:59:44.000+0000",
                "URL01": "",
                "URL02": "",
                "URL03": "",
                "Number of URLs": "",
                "WorkLog Action Status": "",
                "Assign WorkLog Flag": "No",
                "WorkLog Action Completed": "",
                "WorkOrder_EntryID": "WO0000000021381",
                "Infra. Change Task Entry ID": "",
                "z1D Copy To Request ID01": "",
                "z1D CHG Template ID": "",
                "z1D Copy To Request ID02": "",
                "z1D Copy To Request ID03": "",
                "SRM WorkLog ID": "",
                "Thumbnail 1": "",
                "Thumbnail 2": "",
                "Thumbnail 3": "",
                "z1D Assigned Group": ""
            },
            "_links": {
                "self": [
                    {
                        "href": "https://helixsjc814-demo-restapi.onbmc.com/api/arsys/v1/entry/WOI:WorkInfo/CWL000000000575"
                    }
                ]
            }
        },
        {
            "values": {
                "Work Log ID": "CWL000000000576",
                "Submitter": "Seth",
                "Submit Date": "2023-08-25T08:08:22.000+0000",
                "Assigned To": "",
                "Last Modified By": "Seth",
                "Last Modified Date": "2023-08-25T08:08:22.000+0000",
                "Status": "Enabled",
                "Short Description": ".",
                "Status History": "",
                "Notifier Listening": "Not Listening",
                "Assignee Groups": "2147480213;2000000129;",
                "Locale": "",
                "InstanceId": "AGGHE12CCOVBFARZXTJYRZXTJYDGAA",
                "Record ID": "AGGHE12CCOVBFARZXTJYRZXTJYDGAA",
                "Mode": "",
                "Vendor Assignee Groups": "",
                "Vendor Assignee Groups_parent": "",
                "Assignee Groups_parent": "",
                "z1G Multi-language": "",
                "z1G Enable French": "",
                "z1G Enable German": "",
                "z1G Enable Spanish": "",
                "z1G Enable User Defined 1": "",
                "z1G Enable User Defined 2": "",
                "z1G InitComplete": "",
                "z1G_Use_Custom_Prefix": "",
                "z1G_ChangeIDPrefix": "",
                "z1G_ChangeTaskIDPrefix": "",
                "z1D_DirtyFlag": "",
                "z1D_DirtyFlagAssociations": "",
                "z1D_Topic": "",
                "z1D_PrefixResult": "",
                "z1D_PrefixHolder": "",
                "z1D_UserAction": "",
                "DataTags": "",
                "Needs Attention": "",
                "MessageId": "",
                "SR_Instanceid": "SWGHE12CCOVBFARZXTJYRZXTJYDGAC",
                "z1D_WorkInfoToolTip_Info": "",
                "Attachment #1": "",
                "z1D_FileNameAttach2": "",
                "z1D_FileNameAttach3": "",
                "z1D_WorkInfoNote_DefaultMsg": "",
                "z1D_WorkInfo_NoteDefaultMsg": "",
                "z1D_WorkInfo_FileDefaultMsg": "",
                "z1D_WorkInfoFile_DefaultMsg": "",
                "AttachmentSourceFormName": "",
                "AttachmentSourceGUID": "",
                "z1D_ConfirmGroup": "",
                "Chat Session ID": "",
                "Broker Vendor Name": "",
                "Broker Vendor Ticket Id": "",
                "z1D_SkipIfSmartITInstalled": "",
                "NeedsAttentionCCS_Setting": "true",
                "ActivityValueChar_0": "@[Seth Potter]|Seth|(user)",
                "ActivityValueChar_1": "Image attachment",
                "ActivityValueChar_2": "",
                "ActivityValueChar_3": "",
                "ActivityValueSelection_0": "",
                "ActivityValueSelection_1": "",
                "ActivityValueSelection_2": "",
                "ActivityValueSelection_3": "",
                "SV_Activity_Display": "",
                "FileNameAttachment1": "Hi_Image.png",
                "FileNameAttachment2": "",
                "FileNameAttachment3": "",
                "SV_Ticket Summary": "@[Patient Record]|AGGHE12CCOVBFARZR27MRZR27MT3CP|(workorder)",
                "RequestCreatedFromDWP": "No",
                "DWP_SRID": "",
                "DWP_SRInstanceID": "",
                "z1D_WIS": "",
                "IsNotesRTFEnabled": "",
                "z1D_ApplicationGUID": "",
                "z1D_PropertyValue": "",
                "Description": "Image attachment",
                "Assigned Support Organization": "",
                "z1D Char01": "",
                "z1D Char02": "",
                "z1D Char03": "",
                "z1D Char04": "",
                "z1D Action": "",
                "z1D Integer01": "",
                "Assigned Group ID": "",
                "z1D Char05": "",
                "z1D Char06": "",
                "z1D Char07": "",
                "z1D Char08": "",
                "z1D Char09": "",
                "z1D Integer02": "",
                "z1D Integer03": "",
                "z1D Char10": "",
                "z1D Char11": "",
                "z1D Char12": "",
                "z1D Char13": "",
                "z1D Char14": "",
                "z1D Lastcount": "",
                "z1D Char15": "",
                "Detailed Description": "Image attachment",
                "Work Log Submit Date": "2023-08-25T08:08:22.000+0000",
                "Work Log Submitter": "Seth",
                "Work Log Type": "General Information",
                "Work Order ID": "WO0000000021381",
                "Assigned Group": "",
                "Assignee": "",
                "z1D Previous Operation": "",
                "z1D Page Indicator": "",
                "Assigned Support Company": "",
                "Work Order Task ID": "",
                "z1D Char16": "",
                "Shifts Flag": "",
                "Assigned Group Shift Name": "",
                "z1D Close Dialog": "",
                "Assigned Group Shift ID": "",
                "z2AF Work Log01": {
                    "name": "Hi_Image.png",
                    "sizeBytes": 1424,
                    "href": "https://helixsjc814-demo-restapi.onbmc.com/api/arsys/v1/entry/WOI:WorkInfo/CWL000000000576/attach/z2AF%20Work%20Log01"
                },
                "z2AF Work Log02": "",
                "z2AF Work Log03": "",
                "z1D Work Log ID": "",
                "CHG Attachment ID": "",
                "Number of Attachments": 1,
                "Cross Reference ID": "",
                "Communication Source": "",
                "Total Time Spent": 0,
                "View Access": "Internal",
                "z1D Lastcount02": "",
                "z1D Integer04": "",
                "Request Number": "",
                "Work Order Number": "",
                "z1D Action02": "",
                "Secure Work Log": "No",
                "z1D Permission Group ID": "",
                "z1D Permission Group List": "",
                "Assignee Login ID": "",
                "Work Log Date": "2023-08-25T08:08:22.000+0000",
                "URL01": "",
                "URL02": "",
                "URL03": "",
                "Number of URLs": "",
                "WorkLog Action Status": "",
                "Assign WorkLog Flag": "No",
                "WorkLog Action Completed": "",
                "WorkOrder_EntryID": "WO0000000021381",
                "Infra. Change Task Entry ID": "",
                "z1D Copy To Request ID01": "",
                "z1D CHG Template ID": "",
                "z1D Copy To Request ID02": "",
                "z1D Copy To Request ID03": "",
                "SRM WorkLog ID": "",
                "Thumbnail 1": "",
                "Thumbnail 2": "",
                "Thumbnail 3": "",
                "z1D Assigned Group": ""
            },
            "_links": {
                "self": [
                    {
                        "href": "https://helixsjc814-demo-restapi.onbmc.com/api/arsys/v1/entry/WOI:WorkInfo/CWL000000000576"
                    }
                ]
            }
        }
    ],
    "_links": {
        "self": [
            {
                "href": "https://helixsjc814-demo-restapi.onbmc.com/api/arsys/v1/entry/WOI:WorkInfo?q=%27Work%20Order%20ID%27=%22WO0000000021381%22"
            }
        ]
    }
}


for entry in jsonresponse['entries']:
    values = entry['values']
    work_log_id = values['Work Log ID']
    #print(type(values))
    
    # Check if z2AF Work Log objects exist for the entry
    for i in range(1, 4):  # Check for z2AF Work Log01, z2AF Work Log02, and z2AF Work Log03
        attachment_key = f"z2AF Work Log{i:02}"
        attachment = values.get(attachment_key)
        
        if attachment:
            attachment_name = attachment.get('name')
            attachment_size = attachment.get('sizeBytes')
            attachment_href = attachment.get('href')
            
            print(f"Work Log ID: {work_log_id}")
            print(f"Attachment {i} - Name: {attachment_name}, Size: {attachment_size} bytes")
            #print(f"Attachment Href: {attachment_href}")
               
            response = requests.get(attachment_href, headers=methodheaders)
            if response.status_code == 200:
                print("Attachment Content: "+ response.text)
            else:
                print("Failed to download attachment.")
                
            print("-" * 50)